import './globals.css'

import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import Providers from '@/components/context/providers.client'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Youmark',
  description: 'Generated by create next app',
  icons: { apple: "/icon.svg" },
  manifest: "/manifest.json",
  themeColor: "#7c3aed"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster />
          {children}
        </Providers>
      </body>
    </html >
  )
}
